"""Video recap draft generated by the recap assistant worker."""

from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, ForeignKey, Integer, JSON, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class RecapDraft(Base):
    __tablename__ = "recap_drafts"

    id: Mapped[int] = mapped_column(primary_key=True)
    video_id: Mapped[int] = mapped_column(ForeignKey("videos.id"), index=True, nullable=False)
    job_id: Mapped[int] = mapped_column(ForeignKey("processing_jobs.id"), nullable=False)
    content: Mapped[dict[str, Any]] = mapped_column(JSON, nullable=False)
    """Structured draft: titles, hook, beats with timestamps, key quotes."""
    model: Mapped[str] = mapped_column(String(100), nullable=False, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    video: Mapped["Video"] = relationship(back_populates="recap_drafts")
