"""Video thumbnail candidates generated by the thumbnails worker."""

from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class Thumbnail(Base):
    __tablename__ = "thumbnails"

    id: Mapped[int] = mapped_column(primary_key=True)
    video_id: Mapped[int] = mapped_column(ForeignKey("videos.id"), index=True, nullable=False)
    job_id: Mapped[int] = mapped_column(ForeignKey("processing_jobs.id"), nullable=False)
    path: Mapped[str] = mapped_column(String(255), nullable=False)
    """Relative path under the thumbnails directory in storage/outputs."""
    timestamp: Mapped[float] = mapped_column(Float, nullable=False)
    """Source-video time in seconds the frame was taken from."""
    score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    """Higher is better: sharpness plus face prominence."""
    width: Mapped[int] = mapped_column(Integer, nullable=False)
    height: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    video: Mapped["Video"] = relationship(back_populates="thumbnails")
